""

load("//internal/node:node_labels.bzl", "get_node_label", "get_npm_label")

def _basename(p):
    return p.split("/")[-1]

def _fetch(repository_ctx, packages):
    for (name, dep) in packages["dependencies"].items():
        if "resolved" not in dep.keys():
            continue
        output = name.replace("/", "-") + "-" + dep["version"] + ".tgz"
        repository_ctx.download(
            output = output,
            url = dep["resolved"],
            integrity = dep["integrity"],
        )
        # Stuff the tarballs into the npm cache for later (?)
        # Sadly this is way too slow though. Seems like we need to write a
        # js binary that imports pacote and mimics 
        # https://github.com/npm/cli/blob/6141de7b9e866979bf51706fd1be10c54235cf08/lib/cache.js#L97-L103
        # npm = get_npm_label(repository_ctx)
        # repository_ctx.execute(
        #     [npm, "cache", "add", output],
        #     environment = {"npm_config_cache": "."},
        # )

def _npm_fetch_tarballs(repository_ctx):
    build_content = "# Generated by npm_fetch_tarballs.bzl\n"

    # Fetch each tarball listed in the package_lock
    lock_content = json.decode(repository_ctx.read(repository_ctx.attr.package_lock))
    lock_version = lock_content["lockfileVersion"]
    if lock_version < 2:
        fail("npm_fetch_tarballs only works with npm 7 lockfiles (lockfileVersion >= 2), found %s" % lock_version)
    _fetch(repository_ctx, lock_content)
    # recurse one level deeper
    for (name, dep) in lock_content["dependencies"].items():
        if "dependencies" in dep.keys():
            #for (p, attrs) in dep["dependencies"].items():
            _fetch(repository_ctx, dep)

    repository_ctx.template(
        "index.js",
        repository_ctx.path(Label("//internal/npm_tarballs:index.js")),
        {},
    )
    
    result = repository_ctx.execute([
        get_node_label(repository_ctx),
        "index.js",
        repository_ctx.path(repository_ctx.attr.package_lock),
    ])
    if result.return_code:
        fail("index2.ts failed: \nSTDOUT:\n%s\nSTDERR:\n%s" % (result.stdout, result.stderr))

#     # Export all the tarballs
#     repository_ctx.file(
#         "BUILD.bazel",
#         content = """

# filegroup(
#     name = "%s_all",
#     # FIXME: look on the disk and find the files to avoid glob perf penalty
#     srcs = glob([
#         "*.tgz",
#         "_cache/**",
#     ]),
#     visibility = ["//visibility:public"],
# )
# """ % repository_ctx.attr.name,
#     )

npm_fetch_tarballs = repository_rule(
    implementation = _npm_fetch_tarballs,
    attrs = {
        "package_lock": attr.label(mandatory = True),
    },
)
