// Variant of generate_build_file that works with new npm_fetch_deps rule
// TODO(alexeagle): maybe it wants to be factored together into one program?

import * as fs from 'fs'
const Arborist = require('@npmcli/arborist')

async function main(args: string[]) {
  const buildLines =
      [
        '# Generated by fetch_npm_deps via index2.js',
        'package(default_visibility = ["//visibility:public"])',
      ]

      const arb = new Arborist({});
  await arb.loadVirtual();

  buildLines.push('#' + Object.keys(arb.virtualTree))

    fs.readdirSync('.').forEach(file => {
        buildLines.push('filegroup(')
    buildLines.push('    name = "${path.basename(file)}",')
    buildLines.push('    srcs = ["${path.basename(file)}"],')
        buildLines.push(')')
    })

        fs.writeFileSync('BUILD.bazel', buildLines.join('\n'));

        return 0
}


if (require.main == module) {
  (async () => process.exitCode = await main(process.argv.slice(2)))();
}
